/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MethodologiesRouteImport } from './routes/methodologies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as MethodologiesMethodologyIdRouteImport } from './routes/methodologies.$methodologyId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdWorkUnitsRouteImport } from './routes/projects.$projectId.work-units'
import { Route as ProjectsProjectIdTransitionsRouteImport } from './routes/projects.$projectId.transitions'
import { Route as ProjectsProjectIdPinningRouteImport } from './routes/projects.$projectId.pinning'
import { Route as ProjectsProjectIdFactsRouteImport } from './routes/projects.$projectId.facts'
import { Route as ProjectsProjectIdAgentsRouteImport } from './routes/projects.$projectId.agents'
import { Route as MethodologiesMethodologyIdVersionsRouteImport } from './routes/methodologies.$methodologyId.versions'
import { Route as MethodologiesMethodologyIdVersionsVersionIdRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId'
import { Route as MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.work-units'
import { Route as MethodologiesMethodologyIdVersionsVersionIdFactsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.facts'
import { Route as MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.dependency-definitions'
import { Route as MethodologiesMethodologyIdVersionsVersionIdAgentsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.agents'
import { Route as MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.work-units.$workUnitKey'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologiesRoute = MethodologiesRouteImport.update({
  id: '/methodologies',
  path: '/methodologies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const MethodologiesMethodologyIdRoute =
  MethodologiesMethodologyIdRouteImport.update({
    id: '/$methodologyId',
    path: '/$methodologyId',
    getParentRoute: () => MethodologiesRoute,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWorkUnitsRoute =
  ProjectsProjectIdWorkUnitsRouteImport.update({
    id: '/work-units',
    path: '/work-units',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTransitionsRoute =
  ProjectsProjectIdTransitionsRouteImport.update({
    id: '/transitions',
    path: '/transitions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPinningRoute =
  ProjectsProjectIdPinningRouteImport.update({
    id: '/pinning',
    path: '/pinning',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFactsRoute = ProjectsProjectIdFactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAgentsRoute = ProjectsProjectIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const MethodologiesMethodologyIdVersionsRoute =
  MethodologiesMethodologyIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => MethodologiesMethodologyIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdRoute =
  MethodologiesMethodologyIdVersionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => MethodologiesMethodologyIdVersionsRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteImport.update({
    id: '/work-units',
    path: '/work-units',
    getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdFactsRoute =
  MethodologiesMethodologyIdVersionsVersionIdFactsRouteImport.update({
    id: '/facts',
    path: '/facts',
    getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute =
  MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRouteImport.update(
    {
      id: '/dependency-definitions',
      path: '/dependency-definitions',
      getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
    } as any,
  )
const MethodologiesMethodologyIdVersionsVersionIdAgentsRoute =
  MethodologiesMethodologyIdVersionsVersionIdAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteImport.update(
    {
      id: '/$workUnitKey',
      path: '/$workUnitKey',
      getParentRoute: () =>
        MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodologies': typeof MethodologiesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/methodologies/$methodologyId': typeof MethodologiesMethodologyIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/methodologies/$methodologyId/versions': typeof MethodologiesMethodologyIdVersionsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId/pinning': typeof ProjectsProjectIdPinningRoute
  '/projects/$projectId/transitions': typeof ProjectsProjectIdTransitionsRoute
  '/projects/$projectId/work-units': typeof ProjectsProjectIdWorkUnitsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/methodologies/$methodologyId/versions/$versionId': typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
  '/methodologies/$methodologyId/versions/$versionId/agents': typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  '/methodologies/$methodologyId/versions/$versionId/facts': typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodologies': typeof MethodologiesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/methodologies/$methodologyId': typeof MethodologiesMethodologyIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/methodologies/$methodologyId/versions': typeof MethodologiesMethodologyIdVersionsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId/pinning': typeof ProjectsProjectIdPinningRoute
  '/projects/$projectId/transitions': typeof ProjectsProjectIdTransitionsRoute
  '/projects/$projectId/work-units': typeof ProjectsProjectIdWorkUnitsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/methodologies/$methodologyId/versions/$versionId': typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
  '/methodologies/$methodologyId/versions/$versionId/agents': typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  '/methodologies/$methodologyId/versions/$versionId/facts': typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodologies': typeof MethodologiesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/methodologies/$methodologyId': typeof MethodologiesMethodologyIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/methodologies/$methodologyId/versions': typeof MethodologiesMethodologyIdVersionsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRoute
  '/projects/$projectId/pinning': typeof ProjectsProjectIdPinningRoute
  '/projects/$projectId/transitions': typeof ProjectsProjectIdTransitionsRoute
  '/projects/$projectId/work-units': typeof ProjectsProjectIdWorkUnitsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/methodologies/$methodologyId/versions/$versionId': typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
  '/methodologies/$methodologyId/versions/$versionId/agents': typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  '/methodologies/$methodologyId/versions/$versionId/facts': typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/methodologies'
    | '/projects'
    | '/methodologies/$methodologyId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/methodologies/$methodologyId/versions'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/pinning'
    | '/projects/$projectId/transitions'
    | '/projects/$projectId/work-units'
    | '/projects/$projectId/'
    | '/methodologies/$methodologyId/versions/$versionId'
    | '/methodologies/$methodologyId/versions/$versionId/agents'
    | '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
    | '/methodologies/$methodologyId/versions/$versionId/facts'
    | '/methodologies/$methodologyId/versions/$versionId/work-units'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/methodologies'
    | '/projects'
    | '/methodologies/$methodologyId'
    | '/projects/new'
    | '/methodologies/$methodologyId/versions'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/pinning'
    | '/projects/$projectId/transitions'
    | '/projects/$projectId/work-units'
    | '/projects/$projectId'
    | '/methodologies/$methodologyId/versions/$versionId'
    | '/methodologies/$methodologyId/versions/$versionId/agents'
    | '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
    | '/methodologies/$methodologyId/versions/$versionId/facts'
    | '/methodologies/$methodologyId/versions/$versionId/work-units'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/methodologies'
    | '/projects'
    | '/methodologies/$methodologyId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/methodologies/$methodologyId/versions'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/pinning'
    | '/projects/$projectId/transitions'
    | '/projects/$projectId/work-units'
    | '/projects/$projectId/'
    | '/methodologies/$methodologyId/versions/$versionId'
    | '/methodologies/$methodologyId/versions/$versionId/agents'
    | '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
    | '/methodologies/$methodologyId/versions/$versionId/facts'
    | '/methodologies/$methodologyId/versions/$versionId/work-units'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MethodologiesRoute: typeof MethodologiesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologies': {
      id: '/methodologies'
      path: '/methodologies'
      fullPath: '/methodologies'
      preLoaderRoute: typeof MethodologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/methodologies/$methodologyId': {
      id: '/methodologies/$methodologyId'
      path: '/$methodologyId'
      fullPath: '/methodologies/$methodologyId'
      preLoaderRoute: typeof MethodologiesMethodologyIdRouteImport
      parentRoute: typeof MethodologiesRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/work-units': {
      id: '/projects/$projectId/work-units'
      path: '/work-units'
      fullPath: '/projects/$projectId/work-units'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/transitions': {
      id: '/projects/$projectId/transitions'
      path: '/transitions'
      fullPath: '/projects/$projectId/transitions'
      preLoaderRoute: typeof ProjectsProjectIdTransitionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/pinning': {
      id: '/projects/$projectId/pinning'
      path: '/pinning'
      fullPath: '/projects/$projectId/pinning'
      preLoaderRoute: typeof ProjectsProjectIdPinningRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/facts': {
      id: '/projects/$projectId/facts'
      path: '/facts'
      fullPath: '/projects/$projectId/facts'
      preLoaderRoute: typeof ProjectsProjectIdFactsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/agents': {
      id: '/projects/$projectId/agents'
      path: '/agents'
      fullPath: '/projects/$projectId/agents'
      preLoaderRoute: typeof ProjectsProjectIdAgentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/methodologies/$methodologyId/versions': {
      id: '/methodologies/$methodologyId/versions'
      path: '/versions'
      fullPath: '/methodologies/$methodologyId/versions'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId': {
      id: '/methodologies/$methodologyId/versions/$versionId'
      path: '/$versionId'
      fullPath: '/methodologies/$methodologyId/versions/$versionId'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/work-units': {
      id: '/methodologies/$methodologyId/versions/$versionId/work-units'
      path: '/work-units'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/work-units'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/facts': {
      id: '/methodologies/$methodologyId/versions/$versionId/facts'
      path: '/facts'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/facts'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdFactsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': {
      id: '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
      path: '/dependency-definitions'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/agents': {
      id: '/methodologies/$methodologyId/versions/$versionId/agents'
      path: '/agents'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/agents'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': {
      id: '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
      path: '/$workUnitKey'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute
    }
  }
}

interface MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute
}

const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren: MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute:
      MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute,
  }

const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren,
  )

interface MethodologiesMethodologyIdVersionsVersionIdRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdAgentsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  MethodologiesMethodologyIdVersionsVersionIdFactsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
}

const MethodologiesMethodologyIdVersionsVersionIdRouteChildren: MethodologiesMethodologyIdVersionsVersionIdRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdAgentsRoute:
      MethodologiesMethodologyIdVersionsVersionIdAgentsRoute,
    MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute:
      MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute,
    MethodologiesMethodologyIdVersionsVersionIdFactsRoute:
      MethodologiesMethodologyIdVersionsVersionIdFactsRoute,
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute:
      MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren,
  }

const MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren =
  MethodologiesMethodologyIdVersionsVersionIdRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsVersionIdRouteChildren,
  )

interface MethodologiesMethodologyIdVersionsRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
}

const MethodologiesMethodologyIdVersionsRouteChildren: MethodologiesMethodologyIdVersionsRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdRoute:
      MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren,
  }

const MethodologiesMethodologyIdVersionsRouteWithChildren =
  MethodologiesMethodologyIdVersionsRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsRouteChildren,
  )

interface MethodologiesMethodologyIdRouteChildren {
  MethodologiesMethodologyIdVersionsRoute: typeof MethodologiesMethodologyIdVersionsRouteWithChildren
}

const MethodologiesMethodologyIdRouteChildren: MethodologiesMethodologyIdRouteChildren =
  {
    MethodologiesMethodologyIdVersionsRoute:
      MethodologiesMethodologyIdVersionsRouteWithChildren,
  }

const MethodologiesMethodologyIdRouteWithChildren =
  MethodologiesMethodologyIdRoute._addFileChildren(
    MethodologiesMethodologyIdRouteChildren,
  )

interface MethodologiesRouteChildren {
  MethodologiesMethodologyIdRoute: typeof MethodologiesMethodologyIdRouteWithChildren
}

const MethodologiesRouteChildren: MethodologiesRouteChildren = {
  MethodologiesMethodologyIdRoute: MethodologiesMethodologyIdRouteWithChildren,
}

const MethodologiesRouteWithChildren = MethodologiesRoute._addFileChildren(
  MethodologiesRouteChildren,
)

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAgentsRoute: typeof ProjectsProjectIdAgentsRoute
  ProjectsProjectIdFactsRoute: typeof ProjectsProjectIdFactsRoute
  ProjectsProjectIdPinningRoute: typeof ProjectsProjectIdPinningRoute
  ProjectsProjectIdTransitionsRoute: typeof ProjectsProjectIdTransitionsRoute
  ProjectsProjectIdWorkUnitsRoute: typeof ProjectsProjectIdWorkUnitsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAgentsRoute: ProjectsProjectIdAgentsRoute,
  ProjectsProjectIdFactsRoute: ProjectsProjectIdFactsRoute,
  ProjectsProjectIdPinningRoute: ProjectsProjectIdPinningRoute,
  ProjectsProjectIdTransitionsRoute: ProjectsProjectIdTransitionsRoute,
  ProjectsProjectIdWorkUnitsRoute: ProjectsProjectIdWorkUnitsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MethodologiesRoute: MethodologiesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
