/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MethodologiesRouteImport } from './routes/methodologies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as MethodologiesMethodologyIdRouteImport } from './routes/methodologies.$methodologyId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdWorkflowsRouteImport } from './routes/projects.$projectId.workflows'
import { Route as ProjectsProjectIdWorkUnitsRouteImport } from './routes/projects.$projectId.work-units'
import { Route as ProjectsProjectIdTransitionsRouteImport } from './routes/projects.$projectId.transitions'
import { Route as ProjectsProjectIdPinningRouteImport } from './routes/projects.$projectId.pinning'
import { Route as ProjectsProjectIdFactsRouteImport } from './routes/projects.$projectId.facts'
import { Route as ProjectsProjectIdAgentsRouteImport } from './routes/projects.$projectId.agents'
import { Route as MethodologiesMethodologyIdVersionsRouteImport } from './routes/methodologies.$methodologyId.versions'
import { Route as ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRouteImport } from './routes/projects.$projectId.workflow-executions.$workflowExecutionId'
import { Route as ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteImport } from './routes/projects.$projectId.work-units.$projectWorkUnitId'
import { Route as ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRouteImport } from './routes/projects.$projectId.transition-executions.$transitionExecutionId'
import { Route as ProjectsProjectIdStepExecutionsStepExecutionIdRouteImport } from './routes/projects.$projectId.step-executions.$stepExecutionId'
import { Route as ProjectsProjectIdFactsFactDefinitionIdRouteImport } from './routes/projects.$projectId.facts.$factDefinitionId'
import { Route as MethodologiesMethodologyIdVersionsVersionIdRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId'
import { Route as ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRouteImport } from './routes/projects.$projectId.work-units.$projectWorkUnitId.state-machine'
import { Route as ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteImport } from './routes/projects.$projectId.work-units.$projectWorkUnitId.facts'
import { Route as ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteImport } from './routes/projects.$projectId.work-units.$projectWorkUnitId.artifact-slots'
import { Route as MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.work-units'
import { Route as MethodologiesMethodologyIdVersionsVersionIdFactsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.facts'
import { Route as MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.dependency-definitions'
import { Route as MethodologiesMethodologyIdVersionsVersionIdAgentsRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.agents'
import { Route as ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRouteImport } from './routes/projects.$projectId.work-units.$projectWorkUnitId.facts.$factDefinitionId'
import { Route as ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRouteImport } from './routes/projects.$projectId.work-units.$projectWorkUnitId.artifact-slots.$slotDefinitionId'
import { Route as MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.work-units.$workUnitKey'
import { Route as MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRouteImport } from './routes/methodologies.$methodologyId.versions.$versionId.work-units.$workUnitKey.workflow-editor.$workflowDefinitionId'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologiesRoute = MethodologiesRouteImport.update({
  id: '/methodologies',
  path: '/methodologies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const MethodologiesMethodologyIdRoute =
  MethodologiesMethodologyIdRouteImport.update({
    id: '/$methodologyId',
    path: '/$methodologyId',
    getParentRoute: () => MethodologiesRoute,
  } as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdWorkflowsRoute =
  ProjectsProjectIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdWorkUnitsRoute =
  ProjectsProjectIdWorkUnitsRouteImport.update({
    id: '/work-units',
    path: '/work-units',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdTransitionsRoute =
  ProjectsProjectIdTransitionsRouteImport.update({
    id: '/transitions',
    path: '/transitions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPinningRoute =
  ProjectsProjectIdPinningRouteImport.update({
    id: '/pinning',
    path: '/pinning',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFactsRoute = ProjectsProjectIdFactsRouteImport.update({
  id: '/facts',
  path: '/facts',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdAgentsRoute = ProjectsProjectIdAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const MethodologiesMethodologyIdVersionsRoute =
  MethodologiesMethodologyIdVersionsRouteImport.update({
    id: '/versions',
    path: '/versions',
    getParentRoute: () => MethodologiesMethodologyIdRoute,
  } as any)
const ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute =
  ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRouteImport.update({
    id: '/workflow-executions/$workflowExecutionId',
    path: '/workflow-executions/$workflowExecutionId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteImport.update({
    id: '/$projectWorkUnitId',
    path: '/$projectWorkUnitId',
    getParentRoute: () => ProjectsProjectIdWorkUnitsRoute,
  } as any)
const ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute =
  ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRouteImport.update({
    id: '/transition-executions/$transitionExecutionId',
    path: '/transition-executions/$transitionExecutionId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdStepExecutionsStepExecutionIdRoute =
  ProjectsProjectIdStepExecutionsStepExecutionIdRouteImport.update({
    id: '/step-executions/$stepExecutionId',
    path: '/step-executions/$stepExecutionId',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdFactsFactDefinitionIdRoute =
  ProjectsProjectIdFactsFactDefinitionIdRouteImport.update({
    id: '/$factDefinitionId',
    path: '/$factDefinitionId',
    getParentRoute: () => ProjectsProjectIdFactsRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdRoute =
  MethodologiesMethodologyIdVersionsVersionIdRouteImport.update({
    id: '/$versionId',
    path: '/$versionId',
    getParentRoute: () => MethodologiesMethodologyIdVersionsRoute,
  } as any)
const ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRouteImport.update({
    id: '/state-machine',
    path: '/state-machine',
    getParentRoute: () => ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute,
  } as any)
const ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRoute =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteImport.update({
    id: '/facts',
    path: '/facts',
    getParentRoute: () => ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute,
  } as any)
const ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRoute =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteImport.update({
    id: '/artifact-slots',
    path: '/artifact-slots',
    getParentRoute: () => ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteImport.update({
    id: '/work-units',
    path: '/work-units',
    getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdFactsRoute =
  MethodologiesMethodologyIdVersionsVersionIdFactsRouteImport.update({
    id: '/facts',
    path: '/facts',
    getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
  } as any)
const MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute =
  MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRouteImport.update(
    {
      id: '/dependency-definitions',
      path: '/dependency-definitions',
      getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
    } as any,
  )
const MethodologiesMethodologyIdVersionsVersionIdAgentsRoute =
  MethodologiesMethodologyIdVersionsVersionIdAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => MethodologiesMethodologyIdVersionsVersionIdRoute,
  } as any)
const ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRouteImport.update(
    {
      id: '/$factDefinitionId',
      path: '/$factDefinitionId',
      getParentRoute: () =>
        ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRoute,
    } as any,
  )
const ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRouteImport.update(
    {
      id: '/$slotDefinitionId',
      path: '/$slotDefinitionId',
      getParentRoute: () =>
        ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRoute,
    } as any,
  )
const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteImport.update(
    {
      id: '/$workUnitKey',
      path: '/$workUnitKey',
      getParentRoute: () =>
        MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute,
    } as any,
  )
const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRouteImport.update(
    {
      id: '/workflow-editor/$workflowDefinitionId',
      path: '/workflow-editor/$workflowDefinitionId',
      getParentRoute: () =>
        MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodologies': typeof MethodologiesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/methodologies/$methodologyId': typeof MethodologiesMethodologyIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/methodologies/$methodologyId/versions': typeof MethodologiesMethodologyIdVersionsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRouteWithChildren
  '/projects/$projectId/pinning': typeof ProjectsProjectIdPinningRoute
  '/projects/$projectId/transitions': typeof ProjectsProjectIdTransitionsRoute
  '/projects/$projectId/work-units': typeof ProjectsProjectIdWorkUnitsRouteWithChildren
  '/projects/$projectId/workflows': typeof ProjectsProjectIdWorkflowsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/methodologies/$methodologyId/versions/$versionId': typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
  '/projects/$projectId/facts/$factDefinitionId': typeof ProjectsProjectIdFactsFactDefinitionIdRoute
  '/projects/$projectId/step-executions/$stepExecutionId': typeof ProjectsProjectIdStepExecutionsStepExecutionIdRoute
  '/projects/$projectId/transition-executions/$transitionExecutionId': typeof ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute
  '/projects/$projectId/work-units/$projectWorkUnitId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteWithChildren
  '/projects/$projectId/workflow-executions/$workflowExecutionId': typeof ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute
  '/methodologies/$methodologyId/versions/$versionId/agents': typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  '/methodologies/$methodologyId/versions/$versionId/facts': typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/facts': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/state-machine': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute
  '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodologies': typeof MethodologiesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/methodologies/$methodologyId': typeof MethodologiesMethodologyIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/methodologies/$methodologyId/versions': typeof MethodologiesMethodologyIdVersionsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRouteWithChildren
  '/projects/$projectId/pinning': typeof ProjectsProjectIdPinningRoute
  '/projects/$projectId/transitions': typeof ProjectsProjectIdTransitionsRoute
  '/projects/$projectId/work-units': typeof ProjectsProjectIdWorkUnitsRouteWithChildren
  '/projects/$projectId/workflows': typeof ProjectsProjectIdWorkflowsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/methodologies/$methodologyId/versions/$versionId': typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
  '/projects/$projectId/facts/$factDefinitionId': typeof ProjectsProjectIdFactsFactDefinitionIdRoute
  '/projects/$projectId/step-executions/$stepExecutionId': typeof ProjectsProjectIdStepExecutionsStepExecutionIdRoute
  '/projects/$projectId/transition-executions/$transitionExecutionId': typeof ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute
  '/projects/$projectId/work-units/$projectWorkUnitId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteWithChildren
  '/projects/$projectId/workflow-executions/$workflowExecutionId': typeof ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute
  '/methodologies/$methodologyId/versions/$versionId/agents': typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  '/methodologies/$methodologyId/versions/$versionId/facts': typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/facts': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/state-machine': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute
  '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/methodologies': typeof MethodologiesRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/methodologies/$methodologyId': typeof MethodologiesMethodologyIdRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/methodologies/$methodologyId/versions': typeof MethodologiesMethodologyIdVersionsRouteWithChildren
  '/projects/$projectId/agents': typeof ProjectsProjectIdAgentsRoute
  '/projects/$projectId/facts': typeof ProjectsProjectIdFactsRouteWithChildren
  '/projects/$projectId/pinning': typeof ProjectsProjectIdPinningRoute
  '/projects/$projectId/transitions': typeof ProjectsProjectIdTransitionsRoute
  '/projects/$projectId/work-units': typeof ProjectsProjectIdWorkUnitsRouteWithChildren
  '/projects/$projectId/workflows': typeof ProjectsProjectIdWorkflowsRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/methodologies/$methodologyId/versions/$versionId': typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
  '/projects/$projectId/facts/$factDefinitionId': typeof ProjectsProjectIdFactsFactDefinitionIdRoute
  '/projects/$projectId/step-executions/$stepExecutionId': typeof ProjectsProjectIdStepExecutionsStepExecutionIdRoute
  '/projects/$projectId/transition-executions/$transitionExecutionId': typeof ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute
  '/projects/$projectId/work-units/$projectWorkUnitId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteWithChildren
  '/projects/$projectId/workflow-executions/$workflowExecutionId': typeof ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute
  '/methodologies/$methodologyId/versions/$versionId/agents': typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  '/methodologies/$methodologyId/versions/$versionId/facts': typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/facts': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/state-machine': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteWithChildren
  '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute
  '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId': typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute
  '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId': typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/methodologies'
    | '/projects'
    | '/methodologies/$methodologyId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/methodologies/$methodologyId/versions'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/pinning'
    | '/projects/$projectId/transitions'
    | '/projects/$projectId/work-units'
    | '/projects/$projectId/workflows'
    | '/projects/$projectId/'
    | '/methodologies/$methodologyId/versions/$versionId'
    | '/projects/$projectId/facts/$factDefinitionId'
    | '/projects/$projectId/step-executions/$stepExecutionId'
    | '/projects/$projectId/transition-executions/$transitionExecutionId'
    | '/projects/$projectId/work-units/$projectWorkUnitId'
    | '/projects/$projectId/workflow-executions/$workflowExecutionId'
    | '/methodologies/$methodologyId/versions/$versionId/agents'
    | '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
    | '/methodologies/$methodologyId/versions/$versionId/facts'
    | '/methodologies/$methodologyId/versions/$versionId/work-units'
    | '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots'
    | '/projects/$projectId/work-units/$projectWorkUnitId/facts'
    | '/projects/$projectId/work-units/$projectWorkUnitId/state-machine'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
    | '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId'
    | '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/methodologies'
    | '/projects'
    | '/methodologies/$methodologyId'
    | '/projects/new'
    | '/methodologies/$methodologyId/versions'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/pinning'
    | '/projects/$projectId/transitions'
    | '/projects/$projectId/work-units'
    | '/projects/$projectId/workflows'
    | '/projects/$projectId'
    | '/methodologies/$methodologyId/versions/$versionId'
    | '/projects/$projectId/facts/$factDefinitionId'
    | '/projects/$projectId/step-executions/$stepExecutionId'
    | '/projects/$projectId/transition-executions/$transitionExecutionId'
    | '/projects/$projectId/work-units/$projectWorkUnitId'
    | '/projects/$projectId/workflow-executions/$workflowExecutionId'
    | '/methodologies/$methodologyId/versions/$versionId/agents'
    | '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
    | '/methodologies/$methodologyId/versions/$versionId/facts'
    | '/methodologies/$methodologyId/versions/$versionId/work-units'
    | '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots'
    | '/projects/$projectId/work-units/$projectWorkUnitId/facts'
    | '/projects/$projectId/work-units/$projectWorkUnitId/state-machine'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
    | '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId'
    | '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/methodologies'
    | '/projects'
    | '/methodologies/$methodologyId'
    | '/projects/$projectId'
    | '/projects/new'
    | '/methodologies/$methodologyId/versions'
    | '/projects/$projectId/agents'
    | '/projects/$projectId/facts'
    | '/projects/$projectId/pinning'
    | '/projects/$projectId/transitions'
    | '/projects/$projectId/work-units'
    | '/projects/$projectId/workflows'
    | '/projects/$projectId/'
    | '/methodologies/$methodologyId/versions/$versionId'
    | '/projects/$projectId/facts/$factDefinitionId'
    | '/projects/$projectId/step-executions/$stepExecutionId'
    | '/projects/$projectId/transition-executions/$transitionExecutionId'
    | '/projects/$projectId/work-units/$projectWorkUnitId'
    | '/projects/$projectId/workflow-executions/$workflowExecutionId'
    | '/methodologies/$methodologyId/versions/$versionId/agents'
    | '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
    | '/methodologies/$methodologyId/versions/$versionId/facts'
    | '/methodologies/$methodologyId/versions/$versionId/work-units'
    | '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots'
    | '/projects/$projectId/work-units/$projectWorkUnitId/facts'
    | '/projects/$projectId/work-units/$projectWorkUnitId/state-machine'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
    | '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId'
    | '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId'
    | '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  MethodologiesRoute: typeof MethodologiesRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodologies': {
      id: '/methodologies'
      path: '/methodologies'
      fullPath: '/methodologies'
      preLoaderRoute: typeof MethodologiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/methodologies/$methodologyId': {
      id: '/methodologies/$methodologyId'
      path: '/$methodologyId'
      fullPath: '/methodologies/$methodologyId'
      preLoaderRoute: typeof MethodologiesMethodologyIdRouteImport
      parentRoute: typeof MethodologiesRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/workflows': {
      id: '/projects/$projectId/workflows'
      path: '/workflows'
      fullPath: '/projects/$projectId/workflows'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/work-units': {
      id: '/projects/$projectId/work-units'
      path: '/work-units'
      fullPath: '/projects/$projectId/work-units'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/transitions': {
      id: '/projects/$projectId/transitions'
      path: '/transitions'
      fullPath: '/projects/$projectId/transitions'
      preLoaderRoute: typeof ProjectsProjectIdTransitionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/pinning': {
      id: '/projects/$projectId/pinning'
      path: '/pinning'
      fullPath: '/projects/$projectId/pinning'
      preLoaderRoute: typeof ProjectsProjectIdPinningRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/facts': {
      id: '/projects/$projectId/facts'
      path: '/facts'
      fullPath: '/projects/$projectId/facts'
      preLoaderRoute: typeof ProjectsProjectIdFactsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/agents': {
      id: '/projects/$projectId/agents'
      path: '/agents'
      fullPath: '/projects/$projectId/agents'
      preLoaderRoute: typeof ProjectsProjectIdAgentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/methodologies/$methodologyId/versions': {
      id: '/methodologies/$methodologyId/versions'
      path: '/versions'
      fullPath: '/methodologies/$methodologyId/versions'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdRoute
    }
    '/projects/$projectId/workflow-executions/$workflowExecutionId': {
      id: '/projects/$projectId/workflow-executions/$workflowExecutionId'
      path: '/workflow-executions/$workflowExecutionId'
      fullPath: '/projects/$projectId/workflow-executions/$workflowExecutionId'
      preLoaderRoute: typeof ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/work-units/$projectWorkUnitId': {
      id: '/projects/$projectId/work-units/$projectWorkUnitId'
      path: '/$projectWorkUnitId'
      fullPath: '/projects/$projectId/work-units/$projectWorkUnitId'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteImport
      parentRoute: typeof ProjectsProjectIdWorkUnitsRoute
    }
    '/projects/$projectId/transition-executions/$transitionExecutionId': {
      id: '/projects/$projectId/transition-executions/$transitionExecutionId'
      path: '/transition-executions/$transitionExecutionId'
      fullPath: '/projects/$projectId/transition-executions/$transitionExecutionId'
      preLoaderRoute: typeof ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/step-executions/$stepExecutionId': {
      id: '/projects/$projectId/step-executions/$stepExecutionId'
      path: '/step-executions/$stepExecutionId'
      fullPath: '/projects/$projectId/step-executions/$stepExecutionId'
      preLoaderRoute: typeof ProjectsProjectIdStepExecutionsStepExecutionIdRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/facts/$factDefinitionId': {
      id: '/projects/$projectId/facts/$factDefinitionId'
      path: '/$factDefinitionId'
      fullPath: '/projects/$projectId/facts/$factDefinitionId'
      preLoaderRoute: typeof ProjectsProjectIdFactsFactDefinitionIdRouteImport
      parentRoute: typeof ProjectsProjectIdFactsRoute
    }
    '/methodologies/$methodologyId/versions/$versionId': {
      id: '/methodologies/$methodologyId/versions/$versionId'
      path: '/$versionId'
      fullPath: '/methodologies/$methodologyId/versions/$versionId'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsRoute
    }
    '/projects/$projectId/work-units/$projectWorkUnitId/state-machine': {
      id: '/projects/$projectId/work-units/$projectWorkUnitId/state-machine'
      path: '/state-machine'
      fullPath: '/projects/$projectId/work-units/$projectWorkUnitId/state-machine'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRouteImport
      parentRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute
    }
    '/projects/$projectId/work-units/$projectWorkUnitId/facts': {
      id: '/projects/$projectId/work-units/$projectWorkUnitId/facts'
      path: '/facts'
      fullPath: '/projects/$projectId/work-units/$projectWorkUnitId/facts'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteImport
      parentRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute
    }
    '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots': {
      id: '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots'
      path: '/artifact-slots'
      fullPath: '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteImport
      parentRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/work-units': {
      id: '/methodologies/$methodologyId/versions/$versionId/work-units'
      path: '/work-units'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/work-units'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/facts': {
      id: '/methodologies/$methodologyId/versions/$versionId/facts'
      path: '/facts'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/facts'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdFactsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/dependency-definitions': {
      id: '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
      path: '/dependency-definitions'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/dependency-definitions'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/agents': {
      id: '/methodologies/$methodologyId/versions/$versionId/agents'
      path: '/agents'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/agents'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRoute
    }
    '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId': {
      id: '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId'
      path: '/$factDefinitionId'
      fullPath: '/projects/$projectId/work-units/$projectWorkUnitId/facts/$factDefinitionId'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRouteImport
      parentRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRoute
    }
    '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId': {
      id: '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId'
      path: '/$slotDefinitionId'
      fullPath: '/projects/$projectId/work-units/$projectWorkUnitId/artifact-slots/$slotDefinitionId'
      preLoaderRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRouteImport
      parentRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey': {
      id: '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
      path: '/$workUnitKey'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute
    }
    '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId': {
      id: '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId'
      path: '/workflow-editor/$workflowDefinitionId'
      fullPath: '/methodologies/$methodologyId/versions/$versionId/work-units/$workUnitKey/workflow-editor/$workflowDefinitionId'
      preLoaderRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRouteImport
      parentRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute
    }
  }
}

interface MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute
}

const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteChildren: MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute:
      MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyWorkflowEditorWorkflowDefinitionIdRoute,
  }

const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteWithChildren =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteChildren,
  )

interface MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteWithChildren
}

const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren: MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRoute:
      MethodologiesMethodologyIdVersionsVersionIdWorkUnitsWorkUnitKeyRouteWithChildren,
  }

const MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren =
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteChildren,
  )

interface MethodologiesMethodologyIdVersionsVersionIdRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdAgentsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdAgentsRoute
  MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute
  MethodologiesMethodologyIdVersionsVersionIdFactsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdFactsRoute
  MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute: typeof MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren
}

const MethodologiesMethodologyIdVersionsVersionIdRouteChildren: MethodologiesMethodologyIdVersionsVersionIdRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdAgentsRoute:
      MethodologiesMethodologyIdVersionsVersionIdAgentsRoute,
    MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute:
      MethodologiesMethodologyIdVersionsVersionIdDependencyDefinitionsRoute,
    MethodologiesMethodologyIdVersionsVersionIdFactsRoute:
      MethodologiesMethodologyIdVersionsVersionIdFactsRoute,
    MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRoute:
      MethodologiesMethodologyIdVersionsVersionIdWorkUnitsRouteWithChildren,
  }

const MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren =
  MethodologiesMethodologyIdVersionsVersionIdRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsVersionIdRouteChildren,
  )

interface MethodologiesMethodologyIdVersionsRouteChildren {
  MethodologiesMethodologyIdVersionsVersionIdRoute: typeof MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren
}

const MethodologiesMethodologyIdVersionsRouteChildren: MethodologiesMethodologyIdVersionsRouteChildren =
  {
    MethodologiesMethodologyIdVersionsVersionIdRoute:
      MethodologiesMethodologyIdVersionsVersionIdRouteWithChildren,
  }

const MethodologiesMethodologyIdVersionsRouteWithChildren =
  MethodologiesMethodologyIdVersionsRoute._addFileChildren(
    MethodologiesMethodologyIdVersionsRouteChildren,
  )

interface MethodologiesMethodologyIdRouteChildren {
  MethodologiesMethodologyIdVersionsRoute: typeof MethodologiesMethodologyIdVersionsRouteWithChildren
}

const MethodologiesMethodologyIdRouteChildren: MethodologiesMethodologyIdRouteChildren =
  {
    MethodologiesMethodologyIdVersionsRoute:
      MethodologiesMethodologyIdVersionsRouteWithChildren,
  }

const MethodologiesMethodologyIdRouteWithChildren =
  MethodologiesMethodologyIdRoute._addFileChildren(
    MethodologiesMethodologyIdRouteChildren,
  )

interface MethodologiesRouteChildren {
  MethodologiesMethodologyIdRoute: typeof MethodologiesMethodologyIdRouteWithChildren
}

const MethodologiesRouteChildren: MethodologiesRouteChildren = {
  MethodologiesMethodologyIdRoute: MethodologiesMethodologyIdRouteWithChildren,
}

const MethodologiesRouteWithChildren = MethodologiesRoute._addFileChildren(
  MethodologiesRouteChildren,
)

interface ProjectsProjectIdFactsRouteChildren {
  ProjectsProjectIdFactsFactDefinitionIdRoute: typeof ProjectsProjectIdFactsFactDefinitionIdRoute
}

const ProjectsProjectIdFactsRouteChildren: ProjectsProjectIdFactsRouteChildren =
  {
    ProjectsProjectIdFactsFactDefinitionIdRoute:
      ProjectsProjectIdFactsFactDefinitionIdRoute,
  }

const ProjectsProjectIdFactsRouteWithChildren =
  ProjectsProjectIdFactsRoute._addFileChildren(
    ProjectsProjectIdFactsRouteChildren,
  )

interface ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteChildren {
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute
}

const ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteChildren: ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteChildren =
  {
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute:
      ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsSlotDefinitionIdRoute,
  }

const ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteWithChildren =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRoute._addFileChildren(
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteChildren,
  )

interface ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteChildren {
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute
}

const ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteChildren: ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteChildren =
  {
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute:
      ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsFactDefinitionIdRoute,
  }

const ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteWithChildren =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRoute._addFileChildren(
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteChildren,
  )

interface ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteChildren {
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteWithChildren
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteWithChildren
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute
}

const ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteChildren: ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteChildren =
  {
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRoute:
      ProjectsProjectIdWorkUnitsProjectWorkUnitIdArtifactSlotsRouteWithChildren,
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRoute:
      ProjectsProjectIdWorkUnitsProjectWorkUnitIdFactsRouteWithChildren,
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute:
      ProjectsProjectIdWorkUnitsProjectWorkUnitIdStateMachineRoute,
  }

const ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteWithChildren =
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute._addFileChildren(
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteChildren,
  )

interface ProjectsProjectIdWorkUnitsRouteChildren {
  ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute: typeof ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteWithChildren
}

const ProjectsProjectIdWorkUnitsRouteChildren: ProjectsProjectIdWorkUnitsRouteChildren =
  {
    ProjectsProjectIdWorkUnitsProjectWorkUnitIdRoute:
      ProjectsProjectIdWorkUnitsProjectWorkUnitIdRouteWithChildren,
  }

const ProjectsProjectIdWorkUnitsRouteWithChildren =
  ProjectsProjectIdWorkUnitsRoute._addFileChildren(
    ProjectsProjectIdWorkUnitsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdAgentsRoute: typeof ProjectsProjectIdAgentsRoute
  ProjectsProjectIdFactsRoute: typeof ProjectsProjectIdFactsRouteWithChildren
  ProjectsProjectIdPinningRoute: typeof ProjectsProjectIdPinningRoute
  ProjectsProjectIdTransitionsRoute: typeof ProjectsProjectIdTransitionsRoute
  ProjectsProjectIdWorkUnitsRoute: typeof ProjectsProjectIdWorkUnitsRouteWithChildren
  ProjectsProjectIdWorkflowsRoute: typeof ProjectsProjectIdWorkflowsRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdStepExecutionsStepExecutionIdRoute: typeof ProjectsProjectIdStepExecutionsStepExecutionIdRoute
  ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute: typeof ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute
  ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute: typeof ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdAgentsRoute: ProjectsProjectIdAgentsRoute,
  ProjectsProjectIdFactsRoute: ProjectsProjectIdFactsRouteWithChildren,
  ProjectsProjectIdPinningRoute: ProjectsProjectIdPinningRoute,
  ProjectsProjectIdTransitionsRoute: ProjectsProjectIdTransitionsRoute,
  ProjectsProjectIdWorkUnitsRoute: ProjectsProjectIdWorkUnitsRouteWithChildren,
  ProjectsProjectIdWorkflowsRoute: ProjectsProjectIdWorkflowsRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
  ProjectsProjectIdStepExecutionsStepExecutionIdRoute:
    ProjectsProjectIdStepExecutionsStepExecutionIdRoute,
  ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute:
    ProjectsProjectIdTransitionExecutionsTransitionExecutionIdRoute,
  ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute:
    ProjectsProjectIdWorkflowExecutionsWorkflowExecutionIdRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  MethodologiesRoute: MethodologiesRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
