import {
  methodologyAgentTypeSeedRows,
  methodologyArtifactSlotDefinitionSeedRows,
  methodologyArtifactSlotTemplateSeedRows,
  methodologyFactDefinitionSeedRows,
  methodologyLifecycleStateSeedRows,
  methodologyLifecycleTransitionSeedRows,
  methodologyTransitionConditionSetSeedRows,
  methodologyLinkTypeDefinitionSeedRows,
  methodologyTransitionWorkflowBindingSeedRows,
  runtimeMethodologyWorkflowActionStepActionItemSeedRows,
  runtimeMethodologyWorkflowActionStepActionSeedRows,
  runtimeMethodologyWorkflowActionStepSeedRows,
  runtimeMethodologyWorkflowAgentStepExplicitReadGrantSeedRows,
  runtimeMethodologyWorkflowAgentStepWriteItemRequirementSeedRows,
  runtimeMethodologyWorkflowAgentStepWriteItemSeedRows,
  runtimeMethodologyWorkflowAgentStepSeedRows,
  runtimeMethodologyWorkflowBranchRouteConditionSeedRows,
  runtimeMethodologyWorkflowBranchRouteGroupSeedRows,
  runtimeMethodologyWorkflowBranchRouteSeedRows,
  runtimeMethodologyWorkflowBranchStepSeedRows,
  runtimeMethodologyWorkflowContextFactArtifactReferenceSeedRows,
  runtimeMethodologyWorkflowContextFactDefinitionSeedRows,
  runtimeMethodologyWorkflowContextFactDraftSpecFactSeedRows,
  runtimeMethodologyWorkflowContextFactDraftSpecSeedRows,
  runtimeMethodologyWorkflowContextFactDraftSpecSelectionSeedRows,
  runtimeMethodologyWorkflowContextFactExternalBindingSeedRows,
  runtimeMethodologyWorkflowContextFactPlainValueSeedRows,
  runtimeMethodologyWorkflowContextFactWorkflowReferenceSeedRows,
  runtimeMethodologyWorkflowFormFieldSeedRows,
  runtimeMethodologyWorkflowInvokeBindingSeedRows,
  runtimeMethodologyWorkflowInvokeStepSeedRows,
  runtimeMethodologyWorkflowInvokeTransitionSeedRows,
  workUnitFactDefinitionSeedRows,
  methodologyWorkUnitTypeSeedRows,
  methodologyWorkflowEdgeSeedRows,
  methodologyWorkflowSeedRows,
  methodologyWorkflowStepSeedRows,
} from "./tables";
import {
  LOCKED_BMAD_DESIGN_TIME_FACT_KEYS,
  LOCKED_BMAD_METHODOLOGY_FACT_KEYS,
  LOCKED_BMAD_SETUP_WORK_UNIT_FACT_KEYS,
  architectureSeedMetadata,
  brainstormingSeedMetadata,
  prdSeedMetadata,
  productBriefSeedMetadata,
  researchSeedMetadata,
  setupSeedMetadata,
  uxDesignSeedMetadata,
} from "./setup/setup-bmad-mapping";

export const METHODOLOGY_CANONICAL_TABLE_SEED_ORDER = [
  "methodology_work_unit_types",
  "methodology_agent_types",
  "work_unit_lifecycle_states",
  "work_unit_lifecycle_transitions",
  "transition_condition_sets",
  "work_unit_fact_definitions",
  "methodology_artifact_slot_definitions",
  "methodology_artifact_slot_templates",
  "methodology_link_type_definitions",
  "methodology_workflows",
  "methodology_workflow_steps",
  "methodology_workflow_context_fact_definitions",
  "methodology_workflow_context_fact_plain_values",
  "methodology_workflow_context_fact_external_bindings",
  "methodology_workflow_context_fact_workflow_references",
  "methodology_workflow_context_fact_artifact_references",
  "methodology_workflow_context_fact_draft_specs",
  "methodology_workflow_context_fact_draft_spec_selections",
  "methodology_workflow_context_fact_draft_spec_facts",
  "methodology_workflow_form_fields",
  "methodology_workflow_agent_steps",
  "methodology_workflow_agent_step_explicit_read_grants",
  "methodology_workflow_agent_step_write_items",
  "methodology_workflow_agent_step_write_item_requirements",
  "methodology_workflow_action_steps",
  "methodology_workflow_action_step_actions",
  "methodology_workflow_action_step_action_items",
  "methodology_workflow_invoke_steps",
  "methodology_workflow_invoke_bindings",
  "methodology_workflow_invoke_transitions",
  "methodology_workflow_branch_steps",
  "methodology_workflow_branch_routes",
  "methodology_workflow_branch_route_groups",
  "methodology_workflow_branch_route_conditions",
  "methodology_workflow_edges",
  "methodology_transition_workflow_bindings",
  "methodology_fact_definitions",
] as const;

export const methodologyCanonicalTableSeedRows = {
  methodology_work_unit_types: methodologyWorkUnitTypeSeedRows,
  methodology_agent_types: methodologyAgentTypeSeedRows,
  work_unit_lifecycle_states: methodologyLifecycleStateSeedRows,
  work_unit_lifecycle_transitions: methodologyLifecycleTransitionSeedRows,
  transition_condition_sets: methodologyTransitionConditionSetSeedRows,
  work_unit_fact_definitions: workUnitFactDefinitionSeedRows,
  methodology_artifact_slot_definitions: methodologyArtifactSlotDefinitionSeedRows,
  methodology_artifact_slot_templates: methodologyArtifactSlotTemplateSeedRows,
  methodology_link_type_definitions: methodologyLinkTypeDefinitionSeedRows,
  methodology_workflows: methodologyWorkflowSeedRows,
  methodology_workflow_steps: methodologyWorkflowStepSeedRows,
  methodology_workflow_context_fact_definitions:
    runtimeMethodologyWorkflowContextFactDefinitionSeedRows,
  methodology_workflow_context_fact_plain_values:
    runtimeMethodologyWorkflowContextFactPlainValueSeedRows,
  methodology_workflow_context_fact_external_bindings:
    runtimeMethodologyWorkflowContextFactExternalBindingSeedRows,
  methodology_workflow_context_fact_workflow_references:
    runtimeMethodologyWorkflowContextFactWorkflowReferenceSeedRows,
  methodology_workflow_context_fact_artifact_references:
    runtimeMethodologyWorkflowContextFactArtifactReferenceSeedRows,
  methodology_workflow_context_fact_draft_specs:
    runtimeMethodologyWorkflowContextFactDraftSpecSeedRows,
  methodology_workflow_context_fact_draft_spec_selections:
    runtimeMethodologyWorkflowContextFactDraftSpecSelectionSeedRows,
  methodology_workflow_context_fact_draft_spec_facts:
    runtimeMethodologyWorkflowContextFactDraftSpecFactSeedRows,
  methodology_workflow_form_fields: runtimeMethodologyWorkflowFormFieldSeedRows,
  methodology_workflow_agent_steps: runtimeMethodologyWorkflowAgentStepSeedRows,
  methodology_workflow_agent_step_explicit_read_grants:
    runtimeMethodologyWorkflowAgentStepExplicitReadGrantSeedRows,
  methodology_workflow_agent_step_write_items: runtimeMethodologyWorkflowAgentStepWriteItemSeedRows,
  methodology_workflow_agent_step_write_item_requirements:
    runtimeMethodologyWorkflowAgentStepWriteItemRequirementSeedRows,
  methodology_workflow_action_steps: runtimeMethodologyWorkflowActionStepSeedRows,
  methodology_workflow_action_step_actions: runtimeMethodologyWorkflowActionStepActionSeedRows,
  methodology_workflow_action_step_action_items:
    runtimeMethodologyWorkflowActionStepActionItemSeedRows,
  methodology_workflow_invoke_steps: runtimeMethodologyWorkflowInvokeStepSeedRows,
  methodology_workflow_invoke_bindings: runtimeMethodologyWorkflowInvokeBindingSeedRows,
  methodology_workflow_invoke_transitions: runtimeMethodologyWorkflowInvokeTransitionSeedRows,
  methodology_workflow_branch_steps: runtimeMethodologyWorkflowBranchStepSeedRows,
  methodology_workflow_branch_routes: runtimeMethodologyWorkflowBranchRouteSeedRows,
  methodology_workflow_branch_route_groups: runtimeMethodologyWorkflowBranchRouteGroupSeedRows,
  methodology_workflow_branch_route_conditions:
    runtimeMethodologyWorkflowBranchRouteConditionSeedRows,
  methodology_workflow_edges: methodologyWorkflowEdgeSeedRows,
  methodology_transition_workflow_bindings: methodologyTransitionWorkflowBindingSeedRows,
  methodology_fact_definitions: methodologyFactDefinitionSeedRows,
} as const;

export const methodologySeedSlices = {
  slice_a_setup: setupSeedMetadata,
  slice_a_brainstorming: brainstormingSeedMetadata,
  slice_a_research: researchSeedMetadata,
  slice_a_product_brief: productBriefSeedMetadata,
  slice_a_prd: prdSeedMetadata,
  slice_a_ux_design: uxDesignSeedMetadata,
  slice_a_architecture: architectureSeedMetadata,
} as const;

export const methodologyDesignTimeSeedFacts = {
  setupWorkUnitFactDefinitionKeys: LOCKED_BMAD_SETUP_WORK_UNIT_FACT_KEYS,
  methodologyFactDefinitionKeys: LOCKED_BMAD_METHODOLOGY_FACT_KEYS,
  lockedBmadDerivedFactDefinitionKeys: LOCKED_BMAD_DESIGN_TIME_FACT_KEYS,
} as const;

export const methodologyRuntimeSeedPolicy = {
  seedProjectFactInstances: false,
  seedWorkUnitFactInstances: false,
} as const;
