import { relations } from "drizzle-orm";
import {
  index,
  integer,
  jsonb,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { workflowExecutions } from "./workflows";

/**
 * Variable source types indicating where a variable originated from
 */
export type VariableSource =
  | "input" // User-provided input at workflow start
  | "step" // Generated by a step during execution
  | "system" // System-generated (e.g., timestamps, execution IDs)
  | "parent" // Inherited from parent execution
  | "child-propagation" // Propagated up from child execution
  | "migration"; // Historical data migrated from JSONB

/**
 * Variables table - stores typed workflow variables with history tracking
 *
 * Each variable is tied to a specific workflow execution and includes:
 * - JSON value storage for any data type
 * - Optional JSON Schema for validation
 * - Source tracking for audit trail
 *
 * @see AC1 in story 2-M2-variable-system.md
 */
export const variables = pgTable(
  "variables",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    executionId: uuid("execution_id")
      .notNull()
      .references(() => workflowExecutions.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    value: jsonb("value").notNull(),
    valueSchema: jsonb("value_schema"), // Optional JSON Schema for validation
    source: text("source").notNull().$type<VariableSource>(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().notNull(),
  },
  (table) => [
    uniqueIndex("variables_execution_name_idx").on(table.executionId, table.name),
    index("variables_execution_idx").on(table.executionId),
  ],
);

/**
 * Variable history table - audit trail of all variable changes
 *
 * Records every mutation to a variable including:
 * - Previous and new values
 * - What triggered the change (source)
 * - Which step caused the change (if applicable)
 *
 * @see AC2 in story 2-M2-variable-system.md
 */
export const variableHistory = pgTable(
  "variable_history",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    variableId: uuid("variable_id")
      .notNull()
      .references(() => variables.id, { onDelete: "cascade" }),
    previousValue: jsonb("previous_value"), // null for initial creation
    newValue: jsonb("new_value").notNull(),
    source: text("source").notNull().$type<VariableSource>(),
    stepNumber: integer("step_number"),
    changedAt: timestamp("changed_at").defaultNow().notNull(),
  },
  (table) => [index("variable_history_variable_idx").on(table.variableId)],
);

export const variablesRelations = relations(variables, ({ one, many }) => ({
  execution: one(workflowExecutions, {
    fields: [variables.executionId],
    references: [workflowExecutions.id],
  }),
  history: many(variableHistory),
}));

export const variableHistoryRelations = relations(variableHistory, ({ one }) => ({
  variable: one(variables, {
    fields: [variableHistory.variableId],
    references: [variables.id],
  }),
}));

export type Variable = typeof variables.$inferSelect;
export type NewVariable = typeof variables.$inferInsert;
export type VariableHistoryEntry = typeof variableHistory.$inferSelect;
export type NewVariableHistoryEntry = typeof variableHistory.$inferInsert;
