import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const TOOL_FILE_NAME = "chiron-tools.ts";
const TOOL_FILE_VERSION = "v1";
const TOOL_FILE_HEADER = `// Chiron OpenCode Tools ${TOOL_FILE_VERSION}\n`;

const getToolFilePath = (directory?: string) => {
  if (!directory) return null;
  return path.join(directory, ".opencode", TOOL_FILE_NAME);
};

export const ensureChironTools = async (directory?: string) => {
  const toolFilePath = getToolFilePath(directory);
  if (!toolFilePath) return;

  try {
    const existing = await readFile(toolFilePath, "utf8");
    if (existing.startsWith(TOOL_FILE_HEADER)) {
      return;
    }
  } catch {
    // file does not exist
  }

  await mkdir(path.dirname(toolFilePath), { recursive: true });

  const contents = `${TOOL_FILE_HEADER}
// Auto-generated by Chiron. Do not edit manually unless you know what you're doing.

import { tool } from "@opencode-ai/plugin";
import { z } from "zod";

const baseUrl = () => process.env.CHIRON_API_BASE_URL ?? "http://localhost:3000";

export const chiron_context = tool({
  description: "Get Chiron context for the current session/step.",
  parameters: z.object({
    sessionId: z.string().optional(),
    messageId: z.string().optional(),
  }),
  execute: async (input, context) => {
    const sessionId = input.sessionId ?? context.sessionID;
    const messageId = input.messageId ?? context.messageID;
    if (!sessionId || !messageId) {
      return { error: "sessionId and messageId are required" };
    }
    const response = await fetch(baseUrl() + "/api/opencode/chiron_context", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ sessionId, messageId }),
    });
    if (!response.ok) {
      return { error: "chiron_context failed: " + response.status };
    }
    return response.json();
  },
});

export const chiron_actions = tool({
  description: "List available Chiron actions for the current session/step.",
  parameters: z.object({
    sessionId: z.string().optional(),
    messageId: z.string().optional(),
  }),
  execute: async (input, context) => {
    const sessionId = input.sessionId ?? context.sessionID;
    const messageId = input.messageId ?? context.messageID;
    if (!sessionId || !messageId) {
      return { error: "sessionId and messageId are required" };
    }
    const response = await fetch(baseUrl() + "/api/opencode/chiron_actions", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ sessionId, messageId }),
    });
    if (!response.ok) {
      return { error: "chiron_actions failed: " + response.status };
    }
    return response.json();
  },
});

export const chiron_action = tool({
  description: "Execute a Chiron action for the current session/step.",
  parameters: z.object({
    sessionId: z.string().optional(),
    messageId: z.string().optional(),
    action: z.string(),
    args: z.unknown().optional(),
  }),
  execute: async (input, context) => {
    const sessionId = input.sessionId ?? context.sessionID;
    const messageId = input.messageId ?? context.messageID;
    if (!sessionId || !messageId) {
      return { error: "sessionId and messageId are required" };
    }
    const response = await fetch(baseUrl() + "/api/opencode/chiron_action", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        sessionId,
        messageId,
        action: input.action,
        args: input.args ?? {},
      }),
    });
    if (!response.ok) {
      return { error: "chiron_action failed: " + response.status };
    }
    return response.json();
  },
});
`;

  await writeFile(toolFilePath, contents, "utf8");
};
